const $=(id)=>document.getElementById(id);
const roomState={room:null,transcript:[],running:false,turn:0,nextAgentIndex:0,pendingModeratorNote:'',abortController:null};
function defaultAgents(){return[{id:'agent-a',name:'Agent Alpha',role:'Explore the topic, propose ideas, and respond directly to the other Agents.'},{id:'agent-b',name:'Agent Beta',role:'Critique assumptions, identify weaknesses, and improve the discussion.'}];}
let draftAgents=defaultAgents();
function uid(prefix='room'){const bytes=new Uint8Array(9);crypto.getRandomValues(bytes);const token=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return `${prefix}_${token}`;}
function escapeAgent(agent){return{id:String(agent.id||uid('agent')).slice(0,80),name:String(agent.name||'AI Agent').slice(0,80),role:String(agent.role||'Participate constructively in the discussion.').slice(0,1200)};}
function renderAgentEditor(){const root=$('agent-editor');root.replaceChildren();draftAgents.forEach((agent,index)=>{const card=document.createElement('div');card.className='agent-edit-card';const top=document.createElement('div');top.className='agent-card-top';const title=document.createElement('strong');title.textContent=`Agent ${index+1}`;const remove=document.createElement('button');remove.type='button';remove.className='mini-button';remove.textContent='Remove';remove.disabled=draftAgents.length<=2;remove.addEventListener('click',()=>{if(draftAgents.length<=2)return;draftAgents.splice(index,1);renderAgentEditor();});top.append(title,remove);const name=document.createElement('input');name.maxLength=80;name.value=agent.name;name.placeholder='Agent name';name.addEventListener('input',()=>{draftAgents[index].name=name.value});const role=document.createElement('textarea');role.maxLength=1200;role.rows=3;role.value=agent.role;role.placeholder='Role / behavior for this Agent';role.addEventListener('input',()=>{draftAgents[index].role=role.value});card.append(top,name,role);root.append(card);});$('add-agent').disabled=draftAgents.length>=4;}
async function jsonFetch(url,options={}){const response=await fetch(url,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});let data;try{data=await response.json()}catch{data={error:`HTTP ${response.status}`}}if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data;}
function createRoom(){const name=$('room-name').value.trim()||'VAML Agent Room';const topic=$('room-topic').value.trim();const rules=$('room-rules').value.trim();const maxTurns=Math.max(2,Math.min(100,Number($('room-max-turns').value)||12));const delayMs=Math.max(0,Math.min(5000,Number($('room-delay').value)||0));if(!topic){$('room-topic').focus();return;}const agents=draftAgents.map((agent,index)=>escapeAgent({...agent,id:agent.id||`agent-${index+1}`}));roomState.room={id:uid(),name,topic,rules,maxTurns,delayMs,agents,createdAt:new Date().toISOString()};roomState.transcript=[];roomState.turn=0;roomState.nextAgentIndex=0;roomState.pendingModeratorNote='';renderLiveRoom();$('room-live').hidden=false;$('copy-room-id').disabled=false;$('room-badge').textContent='Created';$('room-live').scrollIntoView({behavior:'smooth',block:'start'});}
function renderLiveRoom(){const room=roomState.room;if(!room)return;$('live-room-name').textContent=room.name;$('live-room-meta').textContent=`Created ${new Date(room.createdAt).toLocaleString()} · ${room.agents.length} Agents`;$('live-room-id').textContent=room.id;$('live-topic').textContent=room.topic;$('turn-count').textContent=String(roomState.turn);$('turn-limit').textContent=String(room.maxTurns);const agents=$('live-agents');agents.replaceChildren();room.agents.forEach((agent,index)=>{const node=document.createElement('div');node.className='live-agent';if(index===roomState.nextAgentIndex&&roomState.turn<room.maxTurns)node.classList.add('next');const dot=document.createElement('span');dot.className='agent-dot';const text=document.createElement('span');text.textContent=agent.name;node.append(dot,text);agents.append(node);});renderTranscript();}
function renderTranscript(){const root=$('room-transcript');root.replaceChildren();if(!roomState.transcript.length){const empty=document.createElement('div');empty.className='room-empty';empty.textContent='Room created. Start the room or run a single turn.';root.append(empty);return;}roomState.transcript.forEach((entry)=>{const item=document.createElement('article');item.className=`room-message ${entry.type||'agent'}`;const head=document.createElement('div');head.className='room-message-head';const who=document.createElement('strong');who.textContent=entry.name;const meta=document.createElement('span');meta.textContent=`Turn ${entry.turn} · ${new Date(entry.createdAt).toLocaleTimeString()}`;head.append(who,meta);const body=document.createElement('p');body.textContent=entry.content;item.append(head,body);root.append(item);});root.scrollTop=root.scrollHeight;}
function setStatus(text,state=''){const node=$('live-status');node.textContent=text;node.className='room-badge';if(state)node.classList.add(state);}
function publicTranscript(){return roomState.transcript.slice(-32).map((entry)=>({agentId:entry.agentId||null,name:entry.name,content:entry.content,turn:entry.turn,type:entry.type||'agent'}));}
async function runOneTurn(){const room=roomState.room;if(!room)return;if(roomState.turn>=room.maxTurns){roomState.running=false;setStatus('COMPLETE','complete');syncButtons();return;}const agent=room.agents[roomState.nextAgentIndex];setStatus(`${agent.name} thinking…`,'busy');roomState.abortController=new AbortController();try{const data=await jsonFetch('/api/room-turn',{method:'POST',signal:roomState.abortController.signal,body:JSON.stringify({room:{id:room.id,name:room.name,topic:room.topic,rules:room.rules,maxTurns:room.maxTurns},agent,agents:room.agents,transcript:publicTranscript(),turn:roomState.turn+1,moderatorNote:roomState.pendingModeratorNote})});roomState.pendingModeratorNote='';roomState.turn+=1;roomState.transcript.push({agentId:agent.id,name:agent.name,content:String(data.reply||''),turn:roomState.turn,type:'agent',createdAt:new Date().toISOString()});roomState.nextAgentIndex=(roomState.nextAgentIndex+1)%room.agents.length;setStatus(roomState.turn>=room.maxTurns?'COMPLETE':'READY',roomState.turn>=room.maxTurns?'complete':'');renderLiveRoom();}catch(error){if(error?.name==='AbortError')setStatus('PAUSED');else{setStatus('ERROR','error');roomState.transcript.push({name:'Room system',content:`Agent turn failed: ${error.message}`,turn:roomState.turn+1,type:'system',createdAt:new Date().toISOString()});renderTranscript();roomState.running=false;}}finally{roomState.abortController=null;syncButtons();}}
async function autoLoop(){while(roomState.running&&roomState.room&&roomState.turn<roomState.room.maxTurns){await runOneTurn();if(!roomState.running||!roomState.room||roomState.turn>=roomState.room.maxTurns)break;if(roomState.room.delayMs)await new Promise((resolve)=>setTimeout(resolve,roomState.room.delayMs));}if(roomState.room&&roomState.turn>=roomState.room.maxTurns){roomState.running=false;setStatus('COMPLETE','complete');}syncButtons();}
function syncButtons(){const hasRoom=Boolean(roomState.room);$('start-room').disabled=!hasRoom||roomState.running||roomState.turn>=Number(roomState.room?.maxTurns||0);$('pause-room').disabled=!roomState.running;$('next-turn').disabled=!hasRoom||roomState.running||roomState.turn>=Number(roomState.room?.maxTurns||0)||Boolean(roomState.abortController);}
$('add-agent').addEventListener('click',()=>{if(draftAgents.length>=4)return;const n=draftAgents.length+1;draftAgents.push({id:`agent-${n}`,name:`Agent ${n}`,role:'Add a distinct perspective and respond to the other Agents.'});renderAgentEditor();});
$('create-room').addEventListener('click',createRoom);
$('copy-room-id').addEventListener('click',async()=>{if(roomState.room)await navigator.clipboard.writeText(roomState.room.id);});
$('start-room').addEventListener('click',()=>{if(!roomState.room||roomState.running)return;roomState.running=true;syncButtons();autoLoop();});
$('pause-room').addEventListener('click',()=>{roomState.running=false;roomState.abortController?.abort();setStatus('PAUSED');syncButtons();});
$('next-turn').addEventListener('click',async()=>{if(roomState.running||!roomState.room)return;await runOneTurn();});
$('reset-room').addEventListener('click',()=>{roomState.running=false;roomState.abortController?.abort();roomState.transcript=[];roomState.turn=0;roomState.nextAgentIndex=0;roomState.pendingModeratorNote='';setStatus('READY');renderLiveRoom();syncButtons();});
$('moderator-form').addEventListener('submit',(event)=>{event.preventDefault();const value=$('moderator-note').value.trim();if(!value)return;roomState.pendingModeratorNote=value;$('moderator-note').value='';roomState.transcript.push({name:'Human moderator',content:value,turn:roomState.turn+1,type:'moderator',createdAt:new Date().toISOString()});renderTranscript();});
renderAgentEditor();syncButtons();
